# Generated by Django 4.2.8 on 2024-08-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0003_alter_topic_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('music', models.FileField(upload_to='musics/')),
                ('image', models.ImageField(upload_to='images/')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
