# Generated by Django 4.2.8 on 2024-08-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_alter_topic_table'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='topic.topic'),
        ),
    ]
