# Generated by Django 4.2.8 on 2024-08-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='Topic',
        ),
    ]
