# Generated by Django 4.2.8 on 2024-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_topic_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
